#20-fix-broken-image
RafaelZasas/intro-to-firebase pull request #47
Opened 2021-03-04 05:04 UTC by clarmso

Add default profile image for a user that doesn't have an image. In addition, the default image is displayed when waiting for the profile image to be fetched.

2021-03-05 03:53 UTC, ANDREYDEN requested changes
Nice job! A small, yet functional change. There is currently an error being thrown regarding the `photoURL` being null in `profile.js:10`. It would be nice if that error is also addressed in this PR.

2021-03-05 03:56 UTC, ANDREYDEN commented on public/src/js/profile.js
> +            document.getElementById('small_profile_image').setAttribute('src', userPhoto);
It is good practice to use `{ ... }` even with one-line `if` statements:
```suggestion
        if (userPhoto) {
            document.getElementById('small_profile_image').setAttribute('src', userPhoto);
        }
```

2021-03-05 04:32 UTC, clarmso commented
Regarding `photoURL` being null: Do you mean `user`should be defined before calling `user.photoURL`? I've reorganized the code to guard against calling `user.photoURL`if `user` isn't defined. Please let me know if this is not what you meant.

2021-03-07 00:29 UTC, ANDREYDEN approved these changes
Looks good!

2021-03-07 00:29 UTC, merged